#dataSource config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ASDF.123
    type: com.alibaba.druid.pool.DruidDataSource
    #最大连接数
    druid:
      max-active: 100

#dubbo config
dubbo:
  application:
    name: mall-oms
  registry:
    address: 172.16.141.141:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20900
  consumer:
    check: false

#Mybatis config
mybatis:
  mapper-Locations: classpath:mapper/*.xml
  #output Mybatis sql message
  type-aliases-package: com.xiaobai.mall.oms.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

